// Copyright (c) 2025 Makarand Patwardhan
// SPDX-License-Identifier: AGPL-3.0-only

// Auto-generated by drizzle-kit introspect - do not edit manually
import { relations } from "drizzle-orm/relations";
import {  } from "./schema.generated";
