// Auto-generated by drizzle-kit introspect - do not edit manually
import { relations } from "drizzle-orm/relations";
import { users, ownerNameAliases, documents, providerConfigs } from "./schema.generated";

export const ownerNameAliasesRelations = relations(ownerNameAliases, ({one}) => ({
	user: one(users, {
		fields: [ownerNameAliases.userId],
		references: [users.id]
	}),
}));

export const usersRelations = relations(users, ({many}) => ({
	ownerNameAliases: many(ownerNameAliases),
	documents: many(documents),
	providerConfigs: many(providerConfigs),
}));

export const documentsRelations = relations(documents, ({one}) => ({
	user: one(users, {
		fields: [documents.userId],
		references: [users.id]
	}),
}));

export const providerConfigsRelations = relations(providerConfigs, ({one}) => ({
	user: one(users, {
		fields: [providerConfigs.userId],
		references: [users.id]
	}),
}));
