#!/bin/bash
# Post-introspect processing for drizzle-kit generated files

set -e

SCHEMA_DIR="src/schema"
HEADER='// Auto-generated by drizzle-kit introspect - do not edit manually
'

# Rename files to .generated.ts
mv "$SCHEMA_DIR/schema.ts" "$SCHEMA_DIR/schema.generated.ts"
mv "$SCHEMA_DIR/relations.ts" "$SCHEMA_DIR/relations.generated.ts"

# Fix import in relations file
sed -i '' 's|from "./schema"|from "./schema.generated"|g' "$SCHEMA_DIR/relations.generated.ts"

# Add header comment to both files
for file in "$SCHEMA_DIR/schema.generated.ts" "$SCHEMA_DIR/relations.generated.ts"; do
  echo "$HEADER$(cat "$file")" > "$file"
done

echo "Post-introspect processing complete"
